# ==========================================
# Unreal Engine 임시 및 빌드 생성 파일 항목
# ==========================================
/Binaries
/DerivedDataCache
/Intermediate
/Saved
/Build

# 플러그인 내부의 임시 폴더도 함께 제외
/Plugins/*/Binaries
/Plugins/*/Intermediate

# ==========================================
# IDE (컴파일러 및 개발 도구) 관련 파일 항목
# ==========================================
# Visual Studio
/.vs
/*.sln
/*.suo
/*.sdf
/*.opensdf
/*.VC.db
/*.VC.opendb

# JetBrains Rider / CLion
/.idea

# Visual Studio Code
/.vscode

# ==========================================
# 운영체제(OS) 생성 임시 파일 항목
# ==========================================
.DS_Store
Thumbs.db